base_field: iid
base_table: aggregator_item
core: 8.x
description: ''
status: true
display:
  default:
    display_plugin: default
    id: default
    display_title: Master
    position: 1
    display_options:
      access:
        type: none
        options: {  }
      cache:
        type: none
        options: {  }
      query:
        type: views_query
        options:
          disable_sql_rewrite: false
          distinct: false
          slave: false
          query_comment: false
          query_tags: {  }
      exposed_form:
        type: basic
        options:
          submit_button: Apply
          reset_button: false
          reset_button_label: Reset
          exposed_sorts_label: 'Sort by'
          expose_sort_order: true
          sort_asc_label: Asc
          sort_desc_label: Desc
      pager:
        type: full
        options:
          items_per_page: 10
          offset: 0
          id: 0
          total_pages: 0
          expose:
            items_per_page: '0'
            items_per_page_label: 'Items per page'
            items_per_page_options: '5, 10, 20, 40, 60'
            items_per_page_options_all: false
            items_per_page_options_all_label: '- All -'
            offset: false
            offset_label: Offset
          tags:
            previous: '‹ previous'
            next: 'next ›'
            first: '« first'
            last: 'last »'
          quantity: '9'
      style:
        type: default
      row:
        type: 'entity:aggregator_item'
      fields:
        iid:
          table: aggregator_item
          field: iid
          id: iid
          relationship: none
          group_type: group
          admin_label: ''
          label: 'Item ID'
          exclude: false
          alter:
            alter_text: false
            text: ''
            make_link: false
            path: ''
            absolute: false
            external: false
            replace_spaces: false
            path_case: none
            trim_whitespace: false
            alt: ''
            rel: ''
            link_class: ''
            prefix: ''
            suffix: ''
            target: ''
            nl2br: false
            max_length: ''
            word_boundary: true
            ellipsis: true
            more_link: false
            more_link_text: ''
            more_link_path: ''
            strip_tags: false
            trim: false
            preserve_tags: ''
            html: false
          element_type: ''
          element_class: ''
          element_label_type: ''
          element_label_class: ''
          element_label_colon: true
          element_wrapper_type: ''
          element_wrapper_class: ''
          element_default_classes: true
          empty: ''
          hide_empty: false
          empty_zero: false
          hide_alter_empty: true
          set_precision: '0'
          precision: '0'
          decimal: .
          separator: ','
          format_plural: '0'
          format_plural_singular: '1'
          format_plural_plural: '@count'
          prefix: ''
          suffix: ''
      filters: {  }
      sorts: {  }
      title: 'Aggregator RSS feed'
      header: {  }
      footer: {  }
      empty: {  }
      relationships: {  }
      arguments: {  }
  feed_items_per_category:
    display_plugin: feed
    id: feed_items_per_category
    display_title: 'Feed per category'
    position: 2
    display_options:
      path: aggregator/rss/%
      display_description: ''
      arguments:
        cid:
          id: cid
          table: aggregator_category
          field: cid
          relationship: none
          group_type: group
          admin_label: ''
          default_action: 'not found'
          exception:
            value: all
            title_enable: false
            title: All
          title_enable: false
          title: ''
          breadcrumb_enable: false
          breadcrumb: ''
          default_argument_type: fixed
          default_argument_options:
            argument: ''
          default_argument_skip_url: false
          summary_options:
            base_path: ''
            count: true
            items_per_page: 25
            override: false
          summary:
            sort_order: asc
            number_of_records: 0
            format: default_summary
          specify_validation: false
          validate:
            type: none
            fail: 'not found'
          validate_options: {  }
          break_phrase: false
          not: '0'
          plugin_id: aggregator_category_cid
      defaults:
        arguments: false
  feed_items:
    display_plugin: feed
    id: feed_items
    display_title: Feed
    position: 2
    display_options:
      path: aggregator/rss
      display_description: ''
      defaults:
        arguments: true
label: 'Aggregator RSS feed'
module: views
id: aggregator_rss_feed
tag: aggregator
uuid: 7dfa5cb7-2248-4d52-8c00-cd8e02d1e78e
langcode: en
