# Schema for the views plugins of the User module.

views.argument_validator.user:
  type: mapping
  label: 'User'
  mapping:
    type:
      type: string
      label: 'Type of user filter value to allow'
    restrict_roles:
      type: boolean
      label: 'Restrict user based on role'
    roles:
      type: sequence
      label: 'Restrict to the selected roles'
      sequence:
        - type: string
          label: 'Role'

views.argument_default.user:
  type: mapping
  label: 'User ID from URL'
  mapping:
    user:
      type: boolean
      label: 'Also look for a node and use the node author'

views.argument_default.current_user:
  type: boolean
  label: 'User ID from logged in user'

views.argument_default.node:
  type: boolean
  label: 'Content ID from URL'
