format: restricted_html
name: 'Restricted HTML'
uuid: 5bbb3d96-1278-4390-8200-ed08941c4a8f
status: true
weight: 0
roles:
  - anonymous
cache: true
filters:
  filter_html:
    id: filter_html
    module: filter
    status: true
    weight: -10
    settings:
      allowed_html: '<a> <em> <strong> <cite> <blockquote> <code> <ul> <ol> <li> <dl> <dt> <dd> <h4> <h5> <h6>'
      filter_html_help: true
      filter_html_nofollow: false
  filter_autop:
    id: filter_autop
    module: filter
    status: true
    weight: 0
    settings: {  }
  filter_url:
    id: filter_url
    module: filter
    status: true
    weight: 0
    settings:
      filter_url_length: 72
  filter_htmlcorrector:
    id: filter_htmlcorrector
    module: filter
    status: true
    weight: 10
    settings: {  }
langcode: en
