id: taxonomy_term.forums.default
uuid: c8eab085-8fd3-4545-8600-e13b7d8bb9c4
targetEntityType: taxonomy_term
bundle: forums
mode: default
content:
  name:
    weight: '-5'
    visible: '1'
  description:
    weight: '0'
    visible: '1'
