id: node.field_tags
name: field_tags
entity_type: node
type: taxonomy_term_reference
module: taxonomy
active: '1'
settings:
  allowed_values:
    -
      vocabulary: tags
      parent: 0
locked: '0'
cardinality: '-1'
translatable: '0'
indexes:
  target_id:
    - target_id
status: 1
langcode: und
