base_field: uid
base_table: users
core: 8.x
description: 'Shows the user names of the most recently active users, and the total number of active users.'
status: '1'
display:
  default:
    display_plugin: default
    id: default
    display_title: Master
    position: '1'
    display_options:
      access:
        type: perm
        options:
          perm: 'access user profiles'
      cache:
        type: none
        options: {  }
      query:
        type: views_query
        options:
          disable_sql_rewrite: '0'
          distinct: '0'
          slave: '0'
          query_comment: ''
          query_tags: {  }
      exposed_form:
        type: basic
        options:
          submit_button: Apply
          reset_button: '0'
          reset_button_label: Reset
          exposed_sorts_label: 'Sort by'
          expose_sort_order: '1'
          sort_asc_label: Asc
          sort_desc_label: Desc
      pager:
        type: some
        options:
          items_per_page: '10'
          offset: '0'
      style:
        type: html_list
        options:
          grouping: {  }
          row_class: ''
          default_row_class: '1'
          row_class_special: '1'
          type: ul
          wrapper_class: item-list
          class: ''
      row:
        type: fields
      fields:
        name:
          id: name
          table: users
          field: name
          label: ''
          alter:
            alter_text: '0'
            make_link: '0'
            absolute: '0'
            trim: '0'
            word_boundary: '0'
            ellipsis: '0'
            strip_tags: '0'
            html: '0'
          hide_empty: '0'
          empty_zero: '0'
          link_to_user: '1'
          overwrite_anonymous: '0'
          relationship: none
          group_type: group
          admin_label: ''
          exclude: '0'
          element_type: ''
          element_class: ''
          element_label_type: ''
          element_label_class: ''
          element_label_colon: '1'
          element_wrapper_type: ''
          element_wrapper_class: ''
          element_default_classes: '1'
          empty: ''
          hide_alter_empty: '1'
          anonymous_text: ''
          format_username: '1'
      filters:
        status:
          value: '1'
          table: users
          field: status
          id: status
          expose:
            operator: '0'
          group: '1'
        access:
          id: access
          table: users
          field: access
          relationship: none
          group_type: group
          admin_label: ''
          operator: '>='
          value:
            min: ''
            max: ''
            value: '-15 minutes'
            type: offset
          group: '1'
          exposed: '0'
          expose:
            operator_id: access_op
            label: 'Last access'
            description: 'A user is considered online for this long after they have last viewed a page.'
            use_operator: '0'
            operator: access_op
            identifier: access
            required: '0'
            remember: '0'
            multiple: '0'
            remember_roles:
              authenticated: authenticated
              anonymous: '0'
              administrator: '0'
          is_grouped: '0'
          group_info:
            label: ''
            description: ''
            identifier: ''
            optional: '1'
            widget: select
            multiple: '0'
            remember: '0'
            default_group: All
            default_group_multiple: {  }
            group_items: {  }
          plugin_id: date
      sorts:
        access:
          id: access
          table: users
          field: access
          order: DESC
          relationship: none
          group_type: group
          admin_label: ''
          exposed: '0'
          expose:
            label: ''
          granularity: second
          provider: views
          plugin_id: date
      title: 'Who''s online'
      header:
        result:
          id: result
          table: views
          field: result
          relationship: none
          group_type: group
          admin_label: ''
          empty: '0'
          content: 'There are currently @total users online.'
          plugin_id: result
      footer: {  }
      empty:
        area_text_custom:
          id: area_text_custom
          table: views
          field: area_text_custom
          relationship: none
          group_type: group
          admin_label: ''
          empty: '1'
          tokenize: '0'
          content: 'There are currently 0 users online.'
          plugin_id: text_custom
      relationships: {  }
      arguments: {  }
  who_s_online_block:
    display_plugin: block
    id: who_s_online_block
    display_title: 'Who''s online'
    position: '1'
    display_options:
      block_description: 'Who''s online'
      display_description: 'A list of users that are currently logged in.'
label: 'Who''s online block'
module: views
id: who_s_online
tag: default
uuid: 67a78cad-cf14-4f0d-9705-05d50cd84eaa
langcode: en
