parameters:
    database_driver: pdo_mysql
    database_host: 192.168.56.1
    database_port: null
    database_name: symfonytest
    database_user: root
    database_password: root
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    locale: en
    secret: 8e9bd16ae2c426910178661b7b989d2410
    database_path: null
