# Schema for Configuration files of the entity module.

entity.view_mode.*.*:
  type: mapping
  label: 'Entity view mode settings'
  mapping:
    id:
      type: string
      label: 'ID'
    uuid:
      type: string
      label: 'UUID'
    label:
      type: label
      label: 'The human-readable name of the view mode'
    targetEntityType:
      type: string
      label: 'Target entity type'
    status:
      type: boolean
      label: 'Enabled'
    cache:
      type: boolean
      label: 'Cached'
    langcode:
      type: string
      label: 'Default language'

entity.form_mode.*.*:
  type: mapping
  label: 'Entity form mode settings'
  mapping:
    id:
      type: string
      label: 'ID'
    uuid:
      type: string
      label: 'UUID'
    label:
      type: label
      label: 'The human-readable name of the form mode'
    targetEntityType:
      type: string
      label: 'Target entity type'
    status:
      type: boolean
      label: 'Enabled'
    cache:
      type: boolean
      label: 'Cache'
    langcode:
      type: string
      label: 'Default language'
